import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/includes/header';
import Footer from './components/includes/footer';
import ButtonWpp from './components/button/button-wpp';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body 
        className={inter.className}
      >
        <Header/>
        {children}
        <ButtonWpp/>
        <Footer/>  
      </body>
    </html>
  )
}
